name: organize-downloads
description: Keep Downloads folder organized by file type
enabled: true
run_as_user: cole

trigger:
  type: filesystem
  watch_paths:
    - ~/Downloads
  on_events:
    - file_created
  ignore_patterns:
    - "*.tmp"
    - "*.part"
    - "*.crdownload"
    - ".DS_Store"
  debounce_seconds: 5

action:
  prompt: |
    A new file appeared in Downloads: {{file_path}}

    Move it to the appropriate subfolder based on type:
    - Images (jpg, png, gif, webp, svg) → ~/Pictures/Downloads
    - Documents (pdf, doc, docx, txt, md) → ~/Documents/Downloads
    - Videos (mp4, mov, avi, mkv) → ~/Movies/Downloads
    - Archives (zip, tar, gz, rar) → extract to ~/Downloads/Extracted/
    - Other → leave in place, just log what it is

claude:
  model: sonnet
  allowed_tools:
    - Bash
    - Read
    - Write
    - Glob
    - Grep
  disallowed_tools:
    - WebFetch
    - WebSearch
  add_dirs:
    - ~/Downloads
    - ~/Pictures/Downloads
    - ~/Documents/Downloads
    - ~/Movies/Downloads
  permission_mode: default
  max_budget_usd: 0.25

dry_run: false

on_failure:
  retry: true
  retry_attempts: 2
  retry_delay_seconds: 10
