name: organize-downloads
description: Keep Downloads folder organized by file type
enabled: true
run_as_user: cole

trigger:
  type: filesystem
  watch_paths:
    - ~/Downloads
  on_events:
    - file_created
  ignore_patterns:
    - "*.tmp"
    - "*.part"
    - "*.crdownload"
    - ".DS_Store"
  debounce_seconds: 5

action:
  prompt: |
    A new file appeared in Downloads: {{file_path}}

    First, use the recall tool to check if you have any stored knowledge about
    this type of file or the Downloads folder organization patterns.

    Then organize the file appropriately. If you learn something new about the
    file patterns or organization conventions, use the remember tool to store
    that knowledge for future use.

    Available tools: Read, Write, Bash (for mv/mkdir), Glob, Grep

claude:
  model: sonnet
  allowed_tools:
    - Bash
    - Read
    - Write
    - Glob
    - Grep
  disallowed_tools:
    - WebFetch
    - WebSearch
  add_dirs:
    - ~/Downloads
    - ~/Pictures/Downloads
    - ~/Documents/Downloads
    - ~/Movies/Downloads
  permission_mode: default
  max_budget_usd: 0.25

dry_run: false

on_failure:
  retry: true
  retry_attempts: 2
  retry_delay_seconds: 10
